Feat:Added Rating and Text utilities component
neetukumari4858/component__libraray pull request #9
Opened 2022-02-09 15:23 UTC by neetukumari4858

Feat:Added Rating and Text utilities component
1.Added Rating component
2.Added Text Utilities component

2022-02-09 17:25 UTC, SaurabhChawda approved these changes

2022-02-10 07:13 UTC, t007rushi requested changes

2022-02-10 07:13 UTC, t007rushi commented on components/Rating.css
> +    height: 34.5rem;
the code is breaking for this can use % for right-side container

2022-02-10 07:13 UTC, t007rushi commented on components/Rating.css
> +    height:60rem;
same as above

2022-02-10 07:13 UTC, t007rushi commented on components/Rating.css
> +    background-color: blue;
same as above

2022-02-10 07:13 UTC, t007rushi commented on components/Rating.css
> +    color: #ffb400;
use color variables

2022-02-10 08:39 UTC, krishnakant01 approved these changes
implement the changes suggested by others and you are good to merge.

2022-02-10 11:10 UTC, merged